INSERT INTO employee (id, firstname, lastname, middle_name, role, email, phone_number, password, gender, birth_date,
                      created_date, is_active, salary, time_off_work, card_number, card_expire_date)
VALUES (1, 'Javohir', 'Kuvondikov', 'Azimjon', 'DIRECTOR', 'quvondikovj6@gmail.com', '+998971042969',
        '$2a$10$iE7vZDk1O65eMLhZnO5okeeyF38.Q9hNBZF.Jqwj8S3mRyduo53JS', 'MALE', '1999-11-02 00:00:00.0',
        CURRENT_TIMESTAMP, TRUE, NULL, NULL, NULL, NULL);


INSERT INTO authority (id, authority)
VALUES (1, 'EMPLOYEE_ADD'),
       (2, 'EMPLOYEE_CONFIRM_PHONE_NUMBER'),
       (3, 'EMPLOYEE_GET_CODE_TO_CONFIRM_PHONE_NUMBER'),
       (4, 'EMPLOYEES_GET'),
       (5, 'EMPLOYEE_GET_BY_ID'),
       (6, 'EMPLOYEE_GET_BY_NAME_PHONE'),
       (7, 'EMPLOYEE_EDIT'),
       (8, 'EMPLOYEE_EDIT_ROLE'),
       (9, 'EMPLOYEE_CONFIRM_NEW_PHONE_NUMBER_TO_EDIT'),
       (10, 'EMPLOYEE_GET_CODE_TO_CONFIRM_NEW_PHONE_NUMBER'),
       (11, 'EMPLOYEE_BLOCK'),
       (12, 'EMPLOYEE_UNBLOCK'),
       (13, 'BUYER_GET_BY_ID'),
       (14, 'BUYER_GET_BY_NAME_AND_PHONE'),
       (15, 'BUYER_GET_AMOUNT'),
       (16, 'BUYER_EDIT'),
       (17, 'BUYER_BLOCK'),
       (18, 'BUYER_UNBLOCK'),
       (19, 'BUYER_CONFIRM_NEW_PHONE'),
       (20, 'BUYER_GET_CODE_TO_CONFIRM_NEW_PHONE'),
       (21, 'BUYER_FILL_BALANCE'),
       (22, 'ATTACHMENT_UPLOAD'),
       (23, 'ATTACHMENT_GET_INFO'),
       (24, 'ATTACHMENT_EDIT'),
       (25, 'SELLER_ADD'),
       (26, 'SELLER_GET_BY_FILTER'),
       (27, 'SELLER_GET_BY_ID'),
       (28, 'SELLER_EDIT'),
       (29, 'SELLER_DELETE'),
       (30, 'SELLER_RESTORE'),
       (31, 'REGION_ADD'),
       (32, 'REGION_EDIT'),
       (33, 'REGION_DELETE'),
       (34, 'REGION_COMPLETELY_DELETE'),
       (35, 'BRANCH_ADD'),
       (36, 'BRANCH_EDIT'),
       (37, 'BRANCH_DELETE'),
       (38, 'BRANCH_COMPLETELY_DELETE'),
       (39, 'BRAND_ADD'),
       (40, 'BRAND_EDIT'),
       (41, 'BRAND_DELETE'),
       (42, 'CATEGORY_ADD'),
       (43, 'CATEGORY_EDIT'),
       (44, 'CATEGORY_DELETE'),
       (45, 'PRODUCT_ADD'),
       (46, 'PRODUCT_EDIT'),
       (47, 'PRODUCT_DELETE'),
       (48, 'MAIN_PANEL_ADD'),
       (49, 'MAIN_PANEL_EDIT'),
       (50, 'MAIN_PANEL_DELETE'),
       (51, 'MAIN_PANEL_CONNECT_TO_METHOD'),
       (52, 'MAIN_PANEL_CONNECT_TO_SELLER'),
       (53, 'MAIN_PANEL_CONNECT_TO_CATEGORY'),
       (54, 'MAIN_PANEL_CONNECT_TO_PRODUCT'),
       (55, 'MAIN_PANEL_GET_METHOD_NAMES'),
       (56, 'MAIN_PANEL_GET_UNCONNECTED_PANELS'),
       (57, 'MAIN_PANEL_GET_CONNECTED_PANELS'),
       (58, 'MAIN_PANEL_DISCONNECT_FROM_ANYTHING'),
       (59, 'VIEWED_PRODUCTS_GET_BY_FILTER'),
       (60, 'COMMENT_ADD'),
       (61, 'COMMENT_GET_BY_BUYER_ID'),
       (62, 'COMMENT_GET_UNANSWERED_COMMENTS_BY_PRODUCT_ID'),
       (63, 'COMMENT_REPLY'),
       (64, 'COMMENT_EDIT'),
       (65, 'COMMENT_DELETE'),
       (66, 'BASKET_GET_BY_BUYER_ID'),
       (67, 'BASKET_GET_AMOUNT'),
       (68, 'ORDER_ADD'),
       (69, 'ORDER_GET_BY_PREPARING'),
       (70, 'ORDER_GET_BY_DELIVERING'),
       (71, 'ORDER_GET_BY_RETURNED'),
       (72, 'ORDER_GET_BY_WAITING_CLIENT'),
       (73, 'ORDER_GET_BY_ID'),
       (74, 'ORDER_GET_BY_BUYER_DETAILS'),
       (75, 'ORDER_GET_STAT_BY_BRANCH_ID'),
       (76, 'ORDER_GET_STAT_BY_REGION_ID'),
       (77, 'ORDER_GET_ALL_REGION_STAT'),
       (78, 'ORDER_GET_ALL_BRANCH_STAT_BY_REGION_ID'),
       (79, 'ORDER_GET_BY_BUYER_ID'),
       (80, 'ORDER_GET_TO_HOME_BY_BRANCH_ID'),
       (81, 'ORDER_CHANGE_STATUS'),
       (82, 'ORDER_EDIT'),
       (83, 'ROLE_DIRECTOR'),
       (84, 'ROLE_ADMIN'),
       (85, 'ROLE_SELLER'),
       (86, 'ROLE_BUYER')